#!/bin/bash
#PBS -P VUR
#PBS -l select=1:ncpus=4:ngpus=1:mem=16GB
#PBS -l walltime=2:00:00
#PBS -j oe

cd /home/jshe2377/Video-Frame-Interpolation-Transformer

module load python/3.8.2 magma/2.5.3 openmpi-gcc/3.1.5
source /home/jshe2377/NeuS/neus/bin/activate
module load cuda/10.2.89

CUDA_VISIBLE_DEVICES=1 python main.py --model VFIT_B --dataset atd12k \
--data_root /srv/jshe2377/atd12k_points --batch_size 2
